[phases.setup]
nixpkgs = ["python3", "gcc"]

[phases.install]
cmds = [
  "pip install --upgrade pip",  # Ensure pip is up to date
  "pip install -r requirements.txt"
]

[start]
cmd = "python bot.py"
